# Generated by Django 2.2.6 on 2019-11-07 20:10

from django.db import migrations, models
import lfsgg.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191023_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('short_code', models.CharField(max_length=5)),
                ('logo', models.ImageField(blank=True, null=True, storage=lfsgg.storage_backends.MediaStorage(), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
