apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels:
        pod: django
    spec:
      containers:
        - name: django
          command: ['gunicorn','-b','0.0.0.0:8080','lfsgg.wsgi:application','--env','DJANGO_SETTINGS_MODULE=lfsgg.prod','--log-level','info']
          image: gregmurray/lfsgg:$COMMIT_SHA1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: django-config