# Generated by Django 2.2.6 on 2019-11-19 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lfsgg.storage_backends
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('LOOKING', 'Looking'), ('CONFIRMED', 'Confirmed'), ('REQUESTED', 'Requested'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('request_notes', models.CharField(blank=True, max_length=30, null=True)),
                ('scrim_notes', models.TextField(blank=True, max_length=2000, null=True)),
                ('time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('origin_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_team', to='teams.Team')),
                ('secondary_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_team', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='ScrimRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=12)),
                ('request_notes', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('receiver_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver_team', to='teams.Team')),
                ('scrim', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scrims.Scrim')),
                ('sender_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender_team', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('constant', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=lfsgg.storage_backends.ScrimStorage(), upload_to='')),
                ('thumbnail_updated', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scrims', models.ManyToManyField(related_name='schedule_scrims', to='scrims.Scrim')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_team', to='teams.Team')),
            ],
        ),
    ]
