# Generated by Django 2.2.6 on 2019-10-20 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('LOOKING', 'Looking'), ('CONFIRMED', 'Confirmed'), ('REQUESTED', 'Requested'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], max_length=12)),
                ('request_notes', models.CharField(max_length=30, null=True)),
                ('scrim_notes', models.TextField(max_length=2000, null=True)),
                ('time', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('origin_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_team', to='teams.Team')),
                ('secondary_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secondary_team', to='teams.Team')),
            ],
        ),
    ]
