# Generated by Django 2.2.6 on 2019-11-07 20:10

from django.db import migrations, models
import lfsgg.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('scrims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=lfsgg.storage_backends.ScrimStorage(), upload_to=''),
        ),
    ]
