# Generated by Django 2.2.6 on 2019-11-07 20:10

from django.db import migrations, models
import django.db.models.deletion
import lfsgg.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191107_1510'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.OneToOneField(default=lfsgg.core.models.Game.default_game, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Game'),
        ),
    ]
