apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lfsgg-certificate
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: letsencrypt-staging
  commonName: lfs.gg
  dnsNames:
    - lfs.gg
    - "*.lfs.gg"