apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lfsgg-certificate
spec:
  secretName: letsencrypt-prod
  issuerRef:
    name: letsencrypt-prod
  commonName: lfs.gg
  dnsNames:
    - lfs.gg
    - "api.lfs.gg"